-- Create the Ecom user and set password
CREATE USER ERP IDENTIFIED BY ERP;

-- Grant necessary privileges for a schema owner
GRANT CONNECT, RESOURCE TO ERP;
GRANT CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO ERP;

-- Set the default tablespace and grant unlimited storage quota
ALTER USER ERP DEFAULT TABLESPACE USERS;
ALTER USER ERP QUOTA UNLIMITED ON USERS;


-- Set the current schema to Ecom for convenience
ALTER SESSION SET CURRENT_SCHEMA = ERP;

SELECT * FROM v$version;

------------------------------------------------------------
-- MTL_SYSTEM_ITEMS
------------------------------------------------------------
CREATE TABLE MTL_SYSTEM_ITEMS (
  INVENTORY_ITEM_ID NUMBER PRIMARY KEY,
  ORGANIZATION_ID NUMBER NOT NULL,
  ITEM_CODE VARCHAR2(40) NOT NULL,
  DESCRIPTION VARCHAR2(240) NOT NULL,
  PRIMARY_UOM_CODE VARCHAR2(3) NOT NULL, -- NOS, KGS, MTR, LTR
  ITEM_TYPE VARCHAR2(30) NOT NULL,       -- RAW_MATERIAL, SUB_ASSEMBLY, FINISHED_GOOD, EXPENSE
  ITEM_CATEGORY VARCHAR2(50),            -- MAGNET, CRYO, ELECTRONICS, METAL
  HSN_CODE VARCHAR2(20),                 -- GST HSN
  -- Inventory Controls
  IS_INVENTORY_ITEM VARCHAR2(1) DEFAULT 'Y' CHECK (IS_INVENTORY_ITEM IN ('Y','N')),
  IS_STOCKABLE VARCHAR2(1) DEFAULT 'Y',
  IS_TRANSACTABLE VARCHAR2(1) DEFAULT 'Y',
  -- Tracking Controls
  LOT_CONTROL_CODE VARCHAR2(20) DEFAULT 'NO_CONTROL',   -- NO_CONTROL, FULL_CONTROL
  SERIAL_CONTROL_CODE VARCHAR2(20) DEFAULT 'NO_CONTROL',-- NO_CONTROL, AT_RECEIPT, AT_ISSUE
  SHELF_LIFE_DAYS NUMBER,
  -- Planning
  MRP_PLANNING_CODE VARCHAR2(10) DEFAULT 'MRP',         -- MRP, MPS, REORDER_POINT
  LEAD_TIME_DAYS NUMBER DEFAULT 0,
  FIXED_LEAD_TIME NUMBER DEFAULT 0,
  VARIABLE_LEAD_TIME NUMBER DEFAULT 0,
  SAFETY_STOCK_QUANTITY NUMBER DEFAULT 0,
  MIN_ORDER_QUANTITY NUMBER,
  MAX_ORDER_QUANTITY NUMBER,
  -- Procurement & Sales
  IS_PURCHASEABLE VARCHAR2(1) DEFAULT 'Y',
  IS_SALEABLE VARCHAR2(1) DEFAULT 'N',
  LIST_PRICE_PER_UNIT NUMBER,
  -- Physical
  UNIT_WEIGHT NUMBER,
  WEIGHT_UOM VARCHAR2(3),
  UNIT_VOLUME NUMBER,
  VOLUME_UOM VARCHAR2(3),
  -- Audit
  CREATED_BY VARCHAR2(60) NOT NULL,
  CREATION_DATE DATE DEFAULT SYSDATE,
  LAST_UPDATED_BY VARCHAR2(60),
  LAST_UPDATE_DATE DATE,
  CONSTRAINT UQ_ITEM_ORG UNIQUE (ITEM_CODE, ORGANIZATION_ID)
);

COMMENT ON TABLE MTL_SYSTEM_ITEMS IS 'Central repository for MRI manufacturing components, defining attributes for Inventory, Purchasing, and MRP.';

CREATE SEQUENCE SEQ_MTL_SYSTEM_ITEMS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_MTL_SYSTEM_ITEMS
BEFORE INSERT ON MTL_SYSTEM_ITEMS
FOR EACH ROW
BEGIN
  IF :NEW.INVENTORY_ITEM_ID IS NULL THEN
    SELECT SEQ_MTL_SYSTEM_ITEMS.NEXTVAL INTO :NEW.INVENTORY_ITEM_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- AP_VENDORS
------------------------------------------------------------
CREATE TABLE AP_VENDORS (
  VENDOR_ID NUMBER PRIMARY KEY,
  VENDOR_NAME VARCHAR2(240) NOT NULL,
  VENDOR_CODE VARCHAR2(30) NOT NULL UNIQUE,
  VENDOR_TYPE VARCHAR2(30),              -- OEM, DISTRIBUTOR, SERVICE, IMPORTER
  -- Tax
  GSTIN_NUMBER VARCHAR2(15),
  PAN_NUMBER VARCHAR2(10),
  TAX_REGIME_CODE VARCHAR2(20) DEFAULT 'GST',
  -- Payment
  PAYMENT_TERMS VARCHAR2(50),            -- NET30, NET60, IMMEDIATE
  CURRENCY_CODE VARCHAR2(3) DEFAULT 'INR',
  -- Address
  ADDRESS_LINE1 VARCHAR2(240),
  ADDRESS_LINE2 VARCHAR2(240),
  CITY VARCHAR2(60),
  STATE VARCHAR2(60),
  COUNTRY VARCHAR2(60),
  PIN_CODE VARCHAR2(20),
  -- Contact
  CONTACT_PERSON VARCHAR2(100),
  EMAIL_ADDRESS VARCHAR2(240),
  PHONE_NUMBER VARCHAR2(40),
  -- Status
  IS_ACTIVE VARCHAR2(1) DEFAULT 'Y',
  CREATED_BY VARCHAR2(60),
  CREATION_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_AP_VENDORS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_AP_VENDORS
BEFORE INSERT ON AP_VENDORS
FOR EACH ROW
BEGIN
  IF :NEW.VENDOR_ID IS NULL THEN
    SELECT SEQ_AP_VENDORS.NEXTVAL INTO :NEW.VENDOR_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- AR_CUSTOMERS
------------------------------------------------------------
CREATE TABLE AR_CUSTOMERS (
  CUSTOMER_ID NUMBER PRIMARY KEY,
  CUSTOMER_NAME VARCHAR2(240) NOT NULL,
  CUSTOMER_NUMBER VARCHAR2(30) NOT NULL UNIQUE,
  CUSTOMER_CATEGORY VARCHAR2(30),        -- HOSPITAL, DIAGNOSTIC_CENTER, RESEARCH_INSTITUTE
  ACCOUNT_MANAGER_ID NUMBER,
  CREDIT_LIMIT NUMBER,
  CURRENCY_CODE VARCHAR2(3) DEFAULT 'INR',
  CREATED_BY VARCHAR2(60),
  CREATION_DATE DATE DEFAULT SYSDATE
);

CREATE SEQUENCE SEQ_AR_CUSTOMERS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_AR_CUSTOMERS
BEFORE INSERT ON AR_CUSTOMERS
FOR EACH ROW
BEGIN
  IF :NEW.CUSTOMER_ID IS NULL THEN
    SELECT SEQ_AR_CUSTOMERS.NEXTVAL INTO :NEW.CUSTOMER_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- AR_CUSTOMER_SITES
------------------------------------------------------------
CREATE TABLE AR_CUSTOMER_SITES (
  SITE_ID NUMBER PRIMARY KEY,
  CUSTOMER_ID NUMBER NOT NULL REFERENCES AR_CUSTOMERS (CUSTOMER_ID),
  SITE_USE_CODE VARCHAR2(20),            -- BILL_TO, SHIP_TO, BOTH
  ADDRESS_LABEL VARCHAR2(100),
  ADDRESS_LINE1 VARCHAR2(240),
  CITY VARCHAR2(60),
  STATE VARCHAR2(60),                    -- Place of Supply for GST
  PIN_CODE VARCHAR2(20),
  GSTIN_NUMBER VARCHAR2(15),             -- Site-specific GSTIN
  CONTACT_PERSON VARCHAR2(100),
  PHONE_NUMBER VARCHAR2(40),
  IS_ACTIVE VARCHAR2(1) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_AR_CUSTOMER_SITES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_AR_CUSTOMER_SITES
BEFORE INSERT ON AR_CUSTOMER_SITES
FOR EACH ROW
BEGIN
  IF :NEW.SITE_ID IS NULL THEN
    SELECT SEQ_AR_CUSTOMER_SITES.NEXTVAL INTO :NEW.SITE_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- PRICELIST_HEADERS
------------------------------------------------------------
CREATE TABLE PRICELIST_HEADERS (
  LIST_HEADER_ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(100) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR2(240),
  TYPE VARCHAR2(30) NOT NULL,            -- PURCHASE, SALES
  CURRENCY_CODE VARCHAR2(3) NOT NULL,
  START_DATE DATE DEFAULT SYSDATE,
  END_DATE DATE,
  IS_ACTIVE VARCHAR2(1) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_PRICELIST_HEADERS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PRICELIST_HEADERS
BEFORE INSERT ON PRICELIST_HEADERS
FOR EACH ROW
BEGIN
  IF :NEW.LIST_HEADER_ID IS NULL THEN
    SELECT SEQ_PRICELIST_HEADERS.NEXTVAL INTO :NEW.LIST_HEADER_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- PRICELIST_LINES
------------------------------------------------------------
CREATE TABLE PRICELIST_LINES (
  LIST_LINE_ID NUMBER PRIMARY KEY,
  LIST_HEADER_ID NUMBER NOT NULL REFERENCES PRICELIST_HEADERS (LIST_HEADER_ID),
  ITEM_ID NUMBER NOT NULL REFERENCES MTL_SYSTEM_ITEMS (INVENTORY_ITEM_ID),
  VENDOR_ID NUMBER REFERENCES AP_VENDORS (VENDOR_ID),
  CUSTOMER_ID NUMBER REFERENCES AR_CUSTOMERS (CUSTOMER_ID),
  UNIT_PRICE NUMBER NOT NULL,
  START_DATE DATE DEFAULT SYSDATE,
  END_DATE DATE
);

CREATE SEQUENCE SEQ_PRICELIST_LINES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PRICELIST_LINES
BEFORE INSERT ON PRICELIST_LINES
FOR EACH ROW
BEGIN
  IF :NEW.LIST_LINE_ID IS NULL THEN
    SELECT SEQ_PRICELIST_LINES.NEXTVAL INTO :NEW.LIST_LINE_ID FROM dual;
  END IF;
END;
/

CREATE INDEX IDX_PL_LOOKUP ON PRICELIST_LINES (LIST_HEADER_ID, ITEM_ID, VENDOR_ID);

------------------------------------------------------------
-- PO_INDENT_HEADERS
------------------------------------------------------------
CREATE TABLE PO_INDENT_HEADERS (
  INDENT_HEADER_ID NUMBER PRIMARY KEY,
  INDENT_NUM VARCHAR2(50) NOT NULL UNIQUE,
  INDENT_DATE DATE DEFAULT SYSDATE,
  INDENT_TYPE VARCHAR2(20) DEFAULT 'STANDARD',  -- STANDARD, URGENT
  REQUESTOR_ID NUMBER NOT NULL,
  DEPARTMENT_CODE VARCHAR2(30),                 -- PROD, R&D, MAINTENANCE
  DESCRIPTION VARCHAR2(240),
  STATUS VARCHAR2(20) DEFAULT 'INCOMPLETE',     -- INCOMPLETE, APPROVED, REJECTED, CLOSED
  CREATED_BY VARCHAR2(60)
);

CREATE SEQUENCE SEQ_PO_INDENT_HEADERS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PO_INDENT_HEADERS
BEFORE INSERT ON PO_INDENT_HEADERS
FOR EACH ROW
BEGIN
  IF :NEW.INDENT_HEADER_ID IS NULL THEN
    SELECT SEQ_PO_INDENT_HEADERS.NEXTVAL INTO :NEW.INDENT_HEADER_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- PO_INDENT_LINES
------------------------------------------------------------
CREATE TABLE PO_INDENT_LINES (
  INDENT_LINE_ID NUMBER PRIMARY KEY,
  INDENT_HEADER_ID NUMBER NOT NULL REFERENCES PO_INDENT_HEADERS (INDENT_HEADER_ID),
  LINE_NUM NUMBER NOT NULL,
  ITEM_ID NUMBER NOT NULL REFERENCES MTL_SYSTEM_ITEMS (INVENTORY_ITEM_ID),
  QUANTITY NUMBER NOT NULL,
  NEED_BY_DATE DATE,
  SUGGESTED_VENDOR_ID NUMBER REFERENCES AP_VENDORS (VENDOR_ID),
  STATUS VARCHAR2(20) DEFAULT 'OPEN'           -- OPEN, PO_CREATED, CANCELLED
);

CREATE SEQUENCE SEQ_PO_INDENT_LINES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PO_INDENT_LINES
BEFORE INSERT ON PO_INDENT_LINES
FOR EACH ROW
BEGIN
  IF :NEW.INDENT_LINE_ID IS NULL THEN
    SELECT SEQ_PO_INDENT_LINES.NEXTVAL INTO :NEW.INDENT_LINE_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- PO_HEADERS_ALL
------------------------------------------------------------
CREATE TABLE PO_HEADERS_ALL (
  PO_HEADER_ID NUMBER PRIMARY KEY,
  PO_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
  PO_TYPE VARCHAR2(20) DEFAULT 'STANDARD',      -- STANDARD, BLANKET
  VENDOR_ID NUMBER NOT NULL REFERENCES AP_VENDORS (VENDOR_ID),
  PO_DATE DATE DEFAULT SYSDATE,
  CURRENCY_CODE VARCHAR2(3) NOT NULL,
  EXCHANGE_RATE NUMBER DEFAULT 1,
  BILL_TO_LOCATION_ID NUMBER,
  SHIP_TO_LOCATION_ID NUMBER,
  STATUS VARCHAR2(20) DEFAULT 'INCOMPLETE',     -- INCOMPLETE, APPROVED, OPEN, CLOSED
  APPROVAL_DATE DATE,
  APPROVED_BY NUMBER,
  TOTAL_LINE_AMOUNT NUMBER DEFAULT 0,
  TOTAL_TAX_AMOUNT NUMBER DEFAULT 0,
  GRAND_TOTAL_AMOUNT NUMBER DEFAULT 0
);

CREATE SEQUENCE SEQ_PO_HEADERS_ALL START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PO_HEADERS_ALL
BEFORE INSERT ON PO_HEADERS_ALL
FOR EACH ROW
BEGIN
  IF :NEW.PO_HEADER_ID IS NULL THEN
    SELECT SEQ_PO_HEADERS_ALL.NEXTVAL INTO :NEW.PO_HEADER_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- PO_LINES_ALL
-- Replace virtual LINE_AMOUNT with real column + trigger
------------------------------------------------------------
CREATE TABLE PO_LINES_ALL (
  PO_LINE_ID NUMBER PRIMARY KEY,
  PO_HEADER_ID NUMBER NOT NULL REFERENCES PO_HEADERS_ALL (PO_HEADER_ID),
  LINE_NUM NUMBER NOT NULL,
  ITEM_ID NUMBER NOT NULL REFERENCES MTL_SYSTEM_ITEMS (INVENTORY_ITEM_ID),
  QUANTITY NUMBER NOT NULL,
  UNIT_PRICE NUMBER NOT NULL,     -- Derived from PRICELIST
  LINE_AMOUNT NUMBER,             -- Calculated by trigger (QUANTITY * UNIT_PRICE)
  PROMISED_DATE DATE,
  INDENT_LINE_ID NUMBER REFERENCES PO_INDENT_LINES (INDENT_LINE_ID),
  HSN_CODE VARCHAR2(20),
  GST_TAX_RATE NUMBER
);

CREATE SEQUENCE SEQ_PO_LINES_ALL START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PO_LINES_ALL
BEFORE INSERT OR UPDATE ON PO_LINES_ALL
FOR EACH ROW
BEGIN
  :NEW.LINE_AMOUNT := NVL(:NEW.QUANTITY,0) * NVL(:NEW.UNIT_PRICE,0);
END;
/

CREATE OR REPLACE TRIGGER TRG_PO_LINES_PK
BEFORE INSERT ON PO_LINES_ALL
FOR EACH ROW
BEGIN
  IF :NEW.PO_LINE_ID IS NULL THEN
    SELECT SEQ_PO_LINES_ALL.NEXTVAL INTO :NEW.PO_LINE_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- GST_TAX_CODES
------------------------------------------------------------
CREATE TABLE GST_TAX_CODES (
  TAX_ID NUMBER PRIMARY KEY,
  TAX_CODE VARCHAR2(20) NOT NULL,  -- e.g., GST_18, GST_12, GST_5
  DESCRIPTION VARCHAR2(100),
  CGST_RATE NUMBER DEFAULT 0,
  SGST_RATE NUMBER DEFAULT 0,
  IGST_RATE NUMBER DEFAULT 0,
  EFFECTIVE_FROM DATE,
  EFFECTIVE_TO DATE
);

CREATE SEQUENCE SEQ_GST_TAX_CODES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_GST_TAX_CODES
BEFORE INSERT ON GST_TAX_CODES
FOR EACH ROW
BEGIN
  IF :NEW.TAX_ID IS NULL THEN
    SELECT SEQ_GST_TAX_CODES.NEXTVAL INTO :NEW.TAX_ID FROM dual;
  END IF;
END;
/

INSERT INTO GST_TAX_CODES (TAX_CODE, CGST_RATE, SGST_RATE, IGST_RATE) VALUES ('GST_18', 9, 9, 18);
INSERT INTO GST_TAX_CODES (TAX_CODE, CGST_RATE, SGST_RATE, IGST_RATE) VALUES ('GST_12', 6, 6, 12);
INSERT INTO GST_TAX_CODES (TAX_CODE, CGST_RATE, SGST_RATE, IGST_RATE) VALUES ('GST_5', 2.5, 2.5, 5);

------------------------------------------------------------
-- PO_LINE_TAXES
------------------------------------------------------------
CREATE TABLE PO_LINE_TAXES (
  TAX_LINE_ID NUMBER PRIMARY KEY,
  PO_LINE_ID NUMBER NOT NULL REFERENCES PO_LINES_ALL (PO_LINE_ID),
  TAX_TYPE VARCHAR2(10),           -- CGST, SGST, IGST
  TAX_RATE NUMBER,
  TAX_AMOUNT NUMBER,
  RECOVERABLE_FLAG VARCHAR2(1) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_PO_LINE_TAXES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_PO_LINE_TAXES
BEFORE INSERT ON PO_LINE_TAXES
FOR EACH ROW
BEGIN
  IF :NEW.TAX_LINE_ID IS NULL THEN
    SELECT SEQ_PO_LINE_TAXES.NEXTVAL INTO :NEW.TAX_LINE_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- GST Calculation Package (PKG_GST_CALCULATOR)
------------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_GST_CALCULATOR AS
  PROCEDURE CALCULATE_PO_TAX (P_PO_HEADER_ID IN NUMBER);
END PKG_GST_CALCULATOR;
/

CREATE OR REPLACE PACKAGE BODY PKG_GST_CALCULATOR AS

  PROCEDURE CALCULATE_PO_TAX (P_PO_HEADER_ID IN NUMBER) IS
    V_VENDOR_STATE   VARCHAR2(60);
    V_PLANT_STATE    VARCHAR2(60) := 'Maharashtra';
    V_TOTAL_TAX      NUMBER := 0;
  BEGIN
    -- Get Vendor State
    SELECT V.STATE
      INTO V_VENDOR_STATE
      FROM AP_VENDORS V
      JOIN PO_HEADERS_ALL P ON V.VENDOR_ID = P.VENDOR_ID
     WHERE P.PO_HEADER_ID = P_PO_HEADER_ID;

    -- Clean existing tax lines
    DELETE FROM PO_LINE_TAXES
     WHERE PO_LINE_ID IN (SELECT PO_LINE_ID FROM PO_LINES_ALL WHERE PO_HEADER_ID = P_PO_HEADER_ID);

    -- Loop lines
    FOR L IN (SELECT * FROM PO_LINES_ALL WHERE PO_HEADER_ID = P_PO_HEADER_ID) LOOP
      IF UPPER(TRIM(V_VENDOR_STATE)) = UPPER(TRIM(V_PLANT_STATE)) THEN
        INSERT INTO PO_LINE_TAXES (PO_LINE_ID, TAX_TYPE, TAX_RATE, TAX_AMOUNT)
        VALUES (L.PO_LINE_ID, 'CGST', 9, NVL(L.LINE_AMOUNT,0) * 0.09);

        INSERT INTO PO_LINE_TAXES (PO_LINE_ID, TAX_TYPE, TAX_RATE, TAX_AMOUNT)
        VALUES (L.PO_LINE_ID, 'SGST', 9, NVL(L.LINE_AMOUNT,0) * 0.09);
      ELSE
        INSERT INTO PO_LINE_TAXES (PO_LINE_ID, TAX_TYPE, TAX_RATE, TAX_AMOUNT)
        VALUES (L.PO_LINE_ID, 'IGST', 18, NVL(L.LINE_AMOUNT,0) * 0.18);
      END IF;
    END LOOP;

    -- Header totals
    SELECT NVL(SUM(T.TAX_AMOUNT),0)
      INTO V_TOTAL_TAX
      FROM PO_LINE_TAXES T
      JOIN PO_LINES_ALL L ON T.PO_LINE_ID = L.PO_LINE_ID
     WHERE L.PO_HEADER_ID = P_PO_HEADER_ID;

    UPDATE PO_HEADERS_ALL
       SET TOTAL_TAX_AMOUNT = V_TOTAL_TAX,
           GRAND_TOTAL_AMOUNT = NVL(TOTAL_LINE_AMOUNT,0) + NVL(V_TOTAL_TAX,0)
     WHERE PO_HEADER_ID = P_PO_HEADER_ID;
  END CALCULATE_PO_TAX;

END PKG_GST_CALCULATOR;
/

------------------------------------------------------------
-- RCV_HEADERS
------------------------------------------------------------
CREATE TABLE RCV_HEADERS (
  SHIPMENT_HEADER_ID NUMBER PRIMARY KEY,
  RECEIPT_NUM VARCHAR2(50) NOT NULL UNIQUE,
  VENDOR_ID NUMBER REFERENCES AP_VENDORS (VENDOR_ID),
  SHIPPED_DATE DATE,
  RECEIPT_DATE DATE DEFAULT SYSDATE,
  PACKING_SLIP VARCHAR2(50),
  WAYBILL_NUM VARCHAR2(50),
  GATE_PASS_ID NUMBER
);

CREATE SEQUENCE SEQ_RCV_HEADERS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_RCV_HEADERS
BEFORE INSERT ON RCV_HEADERS
FOR EACH ROW
BEGIN
  IF :NEW.SHIPMENT_HEADER_ID IS NULL THEN
    SELECT SEQ_RCV_HEADERS.NEXTVAL INTO :NEW.SHIPMENT_HEADER_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- RCV_TRANSACTIONS
------------------------------------------------------------
CREATE TABLE RCV_TRANSACTIONS (
  TRANSACTION_ID NUMBER PRIMARY KEY,
  SHIPMENT_HEADER_ID NUMBER NOT NULL REFERENCES RCV_HEADERS (SHIPMENT_HEADER_ID),
  PO_HEADER_ID NUMBER REFERENCES PO_HEADERS_ALL (PO_HEADER_ID),
  PO_LINE_ID NUMBER REFERENCES PO_LINES_ALL (PO_LINE_ID),
  ITEM_ID NUMBER NOT NULL,
  TRANSACTION_TYPE VARCHAR2(20) NOT NULL,   -- RECEIVE, ACCEPT, REJECT, DELIVER
  TRANSACTION_DATE DATE DEFAULT SYSDATE,
  QUANTITY NUMBER NOT NULL,
  UOM_CODE VARCHAR2(3),
  SUBINVENTORY_CODE VARCHAR2(20),
  LOCATOR_ID NUMBER,
  BATCH_NUMBER VARCHAR2(50),
  SERIAL_NUMBER VARCHAR2(50),
  QUALITY_CODE VARCHAR2(20),                 -- PENDING, PASSED, DAMAGED
  COMMENTS VARCHAR2(240)
);

CREATE SEQUENCE SEQ_RCV_TRANSACTIONS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_RCV_TRANSACTIONS
BEFORE INSERT ON RCV_TRANSACTIONS
FOR EACH ROW
BEGIN
  IF :NEW.TRANSACTION_ID IS NULL THEN
    SELECT SEQ_RCV_TRANSACTIONS.NEXTVAL INTO :NEW.TRANSACTION_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- AP_INVOICES_ALL
------------------------------------------------------------
CREATE TABLE AP_INVOICES_ALL (
  INVOICE_ID NUMBER PRIMARY KEY,
  INVOICE_NUM VARCHAR2(50) NOT NULL,
  VENDOR_ID NUMBER REFERENCES AP_VENDORS (VENDOR_ID),
  INVOICE_DATE DATE NOT NULL,
  GL_DATE DATE NOT NULL,
  INVOICE_AMOUNT NUMBER NOT NULL,
  GST_AMOUNT NUMBER,
  STATUS VARCHAR2(20) DEFAULT 'VALIDATED', -- ENTERED, VALIDATED, PAID
  PO_HEADER_ID NUMBER,
  PAYMENT_STATUS_FLAG VARCHAR2(1) DEFAULT 'N'
);

CREATE SEQUENCE SEQ_AP_INVOICES_ALL START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_AP_INVOICES_ALL
BEFORE INSERT ON AP_INVOICES_ALL
FOR EACH ROW
BEGIN
  IF :NEW.INVOICE_ID IS NULL THEN
    SELECT SEQ_AP_INVOICES_ALL.NEXTVAL INTO :NEW.INVOICE_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- GATE_PASS_HEADERS
------------------------------------------------------------
CREATE TABLE GATE_PASS_HEADERS (
  GATE_PASS_ID NUMBER PRIMARY KEY,
  GP_NUMBER VARCHAR2(50) NOT NULL UNIQUE,   -- e.g., GP/IN/2024/0001
  GP_TYPE VARCHAR2(10) NOT NULL CHECK (GP_TYPE IN ('INWARD','OUTWARD')),
  SUB_TYPE VARCHAR2(10) CHECK (SUB_TYPE IN ('RGP','NRGP','PURCHASE','SALES')),
  GP_DATE DATE DEFAULT SYSDATE,
  REQUESTOR_ID NUMBER,
  AUTHORIZER_ID NUMBER,
  SECURITY_GUARD_ID NUMBER,
  VEHICLE_NUMBER VARCHAR2(20) NOT NULL,
  DRIVER_NAME VARCHAR2(100) NOT NULL,
  DRIVER_LICENSE_NO VARCHAR2(50),
  TRANSPORTER_NAME VARCHAR2(100),
  TENTATIVE_RETURN_DATE DATE,
  PARTY_NAME VARCHAR2(240),
  STATUS VARCHAR2(20) DEFAULT 'DRAFT',      -- DRAFT, APPROVED, AT_SECURITY, CLOSED
  REMARKS VARCHAR2(500)
);

CREATE SEQUENCE SEQ_GATE_PASS_HEADERS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_GATE_PASS_HEADERS
BEFORE INSERT ON GATE_PASS_HEADERS
FOR EACH ROW
BEGIN
  IF :NEW.GATE_PASS_ID IS NULL THEN
    SELECT SEQ_GATE_PASS_HEADERS.NEXTVAL INTO :NEW.GATE_PASS_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- GATE_PASS_LINES
------------------------------------------------------------
CREATE TABLE GATE_PASS_LINES (
  GP_LINE_ID NUMBER PRIMARY KEY,
  GATE_PASS_ID NUMBER NOT NULL REFERENCES GATE_PASS_HEADERS (GATE_PASS_ID),
  ITEM_DESCRIPTION VARCHAR2(240),
  QUANTITY NUMBER NOT NULL,
  UOM VARCHAR2(10),
  REFERENCE_DOC_TYPE VARCHAR2(20),        -- PO, INVOICE, CHALLAN
  REFERENCE_DOC_NO VARCHAR2(50),
  IS_RETURNED VARCHAR2(1) DEFAULT 'N',
  ACTUAL_RETURN_DATE DATE
);

CREATE SEQUENCE SEQ_GATE_PASS_LINES START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_GATE_PASS_LINES
BEFORE INSERT ON GATE_PASS_LINES
FOR EACH ROW
BEGIN
  IF :NEW.GP_LINE_ID IS NULL THEN
    SELECT SEQ_GATE_PASS_LINES.NEXTVAL INTO :NEW.GP_LINE_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- PKG_GATE_PASS
------------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_GATE_PASS AS
  PROCEDURE CREATE_INWARD_FROM_PO (
    P_PO_NUMBER IN VARCHAR2,
    P_VEHICLE_NO IN VARCHAR2,
    P_DRIVER_NAME IN VARCHAR2,
    P_USER_ID IN NUMBER,
    P_GP_ID OUT NUMBER
  );

  PROCEDURE AUTHORIZE_OUTWARD_PASS (
    P_GP_ID IN NUMBER,
    P_AUTHORIZER_ID IN NUMBER
  );
END PKG_GATE_PASS;
/

CREATE OR REPLACE PACKAGE BODY PKG_GATE_PASS AS

  PROCEDURE CREATE_INWARD_FROM_PO (
    P_PO_NUMBER IN VARCHAR2,
    P_VEHICLE_NO IN VARCHAR2,
    P_DRIVER_NAME IN VARCHAR2,
    P_USER_ID IN NUMBER,
    P_GP_ID OUT NUMBER
  ) IS
    V_PO_HEADER_ID NUMBER;
    V_VENDOR_NAME  VARCHAR2(240);
  BEGIN
    -- Validate PO
    BEGIN
      SELECT P.PO_HEADER_ID, V.VENDOR_NAME
        INTO V_PO_HEADER_ID, V_VENDOR_NAME
        FROM PO_HEADERS_ALL P
        JOIN AP_VENDORS V ON P.VENDOR_ID = V.VENDOR_ID
       WHERE P.PO_NUMBER = P_PO_NUMBER
         AND P.STATUS = 'APPROVED';
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'Invalid or Unapproved Purchase Order.');
    END;

    -- Create Header
    INSERT INTO GATE_PASS_HEADERS (
      GP_NUMBER, GP_TYPE, SUB_TYPE, GP_DATE, PARTY_NAME,
      VEHICLE_NUMBER, DRIVER_NAME, SECURITY_GUARD_ID, STATUS
    ) VALUES (
      'GP-IN-' || TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
      'INWARD', 'PURCHASE', SYSDATE, V_VENDOR_NAME,
      P_VEHICLE_NO, P_DRIVER_NAME, P_USER_ID, 'AT_SECURITY'
    )
    RETURNING GATE_PASS_ID INTO P_GP_ID;

    -- Create Lines from PO
    INSERT INTO GATE_PASS_LINES (
      GATE_PASS_ID, ITEM_DESCRIPTION, QUANTITY, UOM,
      REFERENCE_DOC_TYPE, REFERENCE_DOC_NO
    )
    SELECT
      P_GP_ID, I.DESCRIPTION, L.QUANTITY, I.PRIMARY_UOM_CODE,
      'PO', P_PO_NUMBER
      FROM PO_LINES_ALL L
      JOIN MTL_SYSTEM_ITEMS I ON L.ITEM_ID = I.INVENTORY_ITEM_ID
     WHERE L.PO_HEADER_ID = V_PO_HEADER_ID;
  END CREATE_INWARD_FROM_PO;

  PROCEDURE AUTHORIZE_OUTWARD_PASS (
    P_GP_ID IN NUMBER,
    P_AUTHORIZER_ID IN NUMBER
  ) IS
  BEGIN
    UPDATE GATE_PASS_HEADERS
       SET STATUS = 'APPROVED',
           AUTHORIZER_ID = P_AUTHORIZER_ID
     WHERE GATE_PASS_ID = P_GP_ID;

    IF SQL%ROWCOUNT = 0 THEN
      RAISE_APPLICATION_ERROR(-20002, 'Gate Pass ID not found.');
    END IF;
  END AUTHORIZE_OUTWARD_PASS;

END PKG_GATE_PASS;
/

------------------------------------------------------------
-- MTL_SECONDARY_INVENTORIES
------------------------------------------------------------
CREATE TABLE MTL_SECONDARY_INVENTORIES (
  SECONDARY_INVENTORY_NAME VARCHAR2(10) NOT NULL,
  ORGANIZATION_ID NUMBER NOT NULL,
  DESCRIPTION VARCHAR2(50),
  DISABLE_DATE DATE,
  ASSET_INVENTORY NUMBER DEFAULT 1,     -- 1=Yes (Valued), 2=No (Expense)
  IS_QUARANTINE VARCHAR2(1) DEFAULT 'N',
  CONSTRAINT PK_SUBINV PRIMARY KEY (SECONDARY_INVENTORY_NAME, ORGANIZATION_ID)
);

------------------------------------------------------------
-- MTL_ITEM_LOCATIONS
------------------------------------------------------------
CREATE TABLE MTL_ITEM_LOCATIONS (
  INVENTORY_LOCATION_ID NUMBER PRIMARY KEY,
  ORGANIZATION_ID NUMBER NOT NULL,
  SUBINVENTORY_CODE VARCHAR2(10) NOT NULL,
  SEGMENT1 VARCHAR2(10),   -- Aisle
  SEGMENT2 VARCHAR2(10),   -- Rack
  SEGMENT3 VARCHAR2(10),   -- Bin
  DESCRIPTION VARCHAR2(240),
  DISABLE_DATE DATE,
  CONSTRAINT FK_LOC_SUBINV FOREIGN KEY (SUBINVENTORY_CODE, ORGANIZATION_ID)
    REFERENCES MTL_SECONDARY_INVENTORIES (SECONDARY_INVENTORY_NAME, ORGANIZATION_ID)
);

CREATE SEQUENCE SEQ_MTL_ITEM_LOCATIONS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_MTL_ITEM_LOCATIONS
BEFORE INSERT ON MTL_ITEM_LOCATIONS
FOR EACH ROW
BEGIN
  IF :NEW.INVENTORY_LOCATION_ID IS NULL THEN
    SELECT SEQ_MTL_ITEM_LOCATIONS.NEXTVAL INTO :NEW.INVENTORY_LOCATION_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- MTL_MATERIAL_TRANSACTIONS
------------------------------------------------------------
CREATE TABLE MTL_MATERIAL_TRANSACTIONS (
  TRANSACTION_ID NUMBER PRIMARY KEY,
  INVENTORY_ITEM_ID NUMBER NOT NULL REFERENCES MTL_SYSTEM_ITEMS (INVENTORY_ITEM_ID),
  ORGANIZATION_ID NUMBER NOT NULL,
  SUBINVENTORY_CODE VARCHAR2(10) NOT NULL,
  LOCATOR_ID NUMBER REFERENCES MTL_ITEM_LOCATIONS (INVENTORY_LOCATION_ID),
  TRANSFER_SUBINVENTORY VARCHAR2(10),
  TRANSACTION_TYPE_ID NUMBER NOT NULL,   -- 1=PO Receipt, 2=Subinv Transfer, 3=WIP Issue, 4=Sales Issue
  TRANSACTION_DATE DATE DEFAULT SYSDATE,
  TRANSACTION_QUANTITY NUMBER NOT NULL,  -- +ve receipt, -ve issue
  TRANSACTION_UOM VARCHAR2(3),
  BATCH_NUMBER VARCHAR2(50),
  SERIAL_NUMBER VARCHAR2(50),
  SOURCE_CODE VARCHAR2(30),              -- PO, ORDER, WIP
  SOURCE_LINE_ID NUMBER,
  CREATED_BY VARCHAR2(60)
);

CREATE SEQUENCE SEQ_MTL_MATERIAL_TRANSACTIONS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_MTL_MATERIAL_TRANSACTIONS
BEFORE INSERT ON MTL_MATERIAL_TRANSACTIONS
FOR EACH ROW
BEGIN
  IF :NEW.TRANSACTION_ID IS NULL THEN
    SELECT SEQ_MTL_MATERIAL_TRANSACTIONS.NEXTVAL INTO :NEW.TRANSACTION_ID FROM dual;
  END IF;
END;
/

CREATE INDEX IDX_MTL_TRX_CALC ON
MTL_MATERIAL_TRANSACTIONS (INVENTORY_ITEM_ID, SUBINVENTORY_CODE, ORGANIZATION_ID);

------------------------------------------------------------
-- VIEW_ONHAND_QUANTITIES
------------------------------------------------------------
CREATE OR REPLACE VIEW VIEW_ONHAND_QUANTITIES AS
SELECT
  INVENTORY_ITEM_ID,
  ORGANIZATION_ID,
  SUBINVENTORY_CODE,
  LOCATOR_ID,
  BATCH_NUMBER,
  SUM(TRANSACTION_QUANTITY) AS ON_HAND_QUANTITY
FROM MTL_MATERIAL_TRANSACTIONS
GROUP BY
  INVENTORY_ITEM_ID,
  ORGANIZATION_ID,
  SUBINVENTORY_CODE,
  LOCATOR_ID,
  BATCH_NUMBER;
  
  ------------------------------------------------------------
-- MRP_PLANS
------------------------------------------------------------
CREATE TABLE MRP_PLANS (
  PLAN_ID NUMBER PRIMARY KEY,
  PLAN_NAME VARCHAR2(50) UNIQUE,
  PLAN_DATE DATE DEFAULT SYSDATE,
  DESCRIPTION VARCHAR2(240)
);

CREATE SEQUENCE SEQ_MRP_PLANS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_MRP_PLANS
BEFORE INSERT ON MRP_PLANS
FOR EACH ROW
BEGIN
  IF :NEW.PLAN_ID IS NULL THEN
    SELECT SEQ_MRP_PLANS.NEXTVAL INTO :NEW.PLAN_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- MRP_GROSS_REQUIREMENTS
------------------------------------------------------------
CREATE TABLE MRP_GROSS_REQUIREMENTS (
  REQUIREMENT_ID NUMBER PRIMARY KEY,
  PLAN_ID NUMBER REFERENCES MRP_PLANS (PLAN_ID),
  INVENTORY_ITEM_ID NUMBER,
  REQUIREMENT_DATE DATE,
  QUANTITY NUMBER,
  SOURCE_TYPE VARCHAR2(20),              -- SALES_ORDER, FORECAST
  SOURCE_ID NUMBER                        -- link to OE_ORDER_LINES_ALL.LINE_ID
);

CREATE SEQUENCE SEQ_MRP_GROSS_REQ START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_MRP_GROSS_REQ
BEFORE INSERT ON MRP_GROSS_REQUIREMENTS
FOR EACH ROW
BEGIN
  IF :NEW.REQUIREMENT_ID IS NULL THEN
    SELECT SEQ_MRP_GROSS_REQ.NEXTVAL INTO :NEW.REQUIREMENT_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- MRP_RECOMMENDATIONS
------------------------------------------------------------
CREATE TABLE MRP_RECOMMENDATIONS (
  RECOMMENDATION_ID NUMBER PRIMARY KEY,
  PLAN_ID NUMBER REFERENCES MRP_PLANS (PLAN_ID),
  INVENTORY_ITEM_ID NUMBER,
  ORDER_TYPE VARCHAR2(20),                -- BUY, MAKE
  SUGGESTED_QUANTITY NUMBER,
  SUGGESTED_ORDER_DATE DATE,
  NEED_BY_DATE DATE,
  ACTION_MESSAGE VARCHAR2(240)
);

CREATE SEQUENCE SEQ_MRP_RECOMMENDATIONS START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_MRP_RECOMMENDATIONS
BEFORE INSERT ON MRP_RECOMMENDATIONS
FOR EACH ROW
BEGIN
  IF :NEW.RECOMMENDATION_ID IS NULL THEN
    SELECT SEQ_MRP_RECOMMENDATIONS.NEXTVAL INTO :NEW.RECOMMENDATION_ID FROM dual;
  END IF;
END;
/

------------------------------------------------------------
-- PKG_MRP_ENGINE
------------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_MRP_ENGINE AS
  PROCEDURE GENERATE_PLAN (P_PLAN_ID IN NUMBER);
END PKG_MRP_ENGINE;
/

CREATE OR REPLACE PACKAGE BODY PKG_MRP_ENGINE AS

  PROCEDURE GENERATE_PLAN (P_PLAN_ID IN NUMBER) IS
    V_ONHAND_QTY  NUMBER;
    V_ONORDER_QTY NUMBER;
    V_NET_QTY     NUMBER;
    V_LEAD_TIME   NUMBER;
  BEGIN
    DELETE FROM MRP_RECOMMENDATIONS WHERE PLAN_ID = P_PLAN_ID;
    DELETE FROM MRP_GROSS_REQUIREMENTS WHERE PLAN_ID = P_PLAN_ID;

    -- Demand: booked Sales Orders
    INSERT INTO MRP_GROSS_REQUIREMENTS (PLAN_ID, INVENTORY_ITEM_ID, REQUIREMENT_DATE, QUANTITY, SOURCE_TYPE, SOURCE_ID)
    SELECT P_PLAN_ID, ITEM_ID, SCHEDULE_SHIP_DATE, QUANTITY, 'SALES_ORDER', LINE_ID
      FROM OE_ORDER_LINES_ALL
     WHERE STATUS = 'BOOKED';

    FOR REC IN (SELECT * FROM MRP_GROSS_REQUIREMENTS WHERE PLAN_ID = P_PLAN_ID ORDER BY REQUIREMENT_DATE) LOOP
      -- On-hand
      SELECT NVL(SUM(ON_HAND_QUANTITY),0) INTO V_ONHAND_QTY
        FROM VIEW_ONHAND_QUANTITIES
       WHERE INVENTORY_ITEM_ID = REC.INVENTORY_ITEM_ID;

      -- Scheduled receipts (Approved POs)
      SELECT NVL(SUM(L.QUANTITY),0) INTO V_ONORDER_QTY
        FROM PO_LINES_ALL L
        JOIN PO_HEADERS_ALL H ON L.PO_HEADER_ID = H.PO_HEADER_ID
       WHERE L.ITEM_ID = REC.INVENTORY_ITEM_ID
         AND H.STATUS = 'APPROVED';

      IF (NVL(V_ONHAND_QTY,0) + NVL(V_ONORDER_QTY,0)) < NVL(REC.QUANTITY,0) THEN
        V_NET_QTY := REC.QUANTITY - (NVL(V_ONHAND_QTY,0) + NVL(V_ONORDER_QTY,0));

        SELECT NVL(LEAD_TIME_DAYS,0) INTO V_LEAD_TIME
          FROM MTL_SYSTEM_ITEMS
         WHERE INVENTORY_ITEM_ID = REC.INVENTORY_ITEM_ID;

        INSERT INTO MRP_RECOMMENDATIONS (
          PLAN_ID, INVENTORY_ITEM_ID, ORDER_TYPE, SUGGESTED_QUANTITY,
          NEED_BY_DATE, SUGGESTED_ORDER_DATE, ACTION_MESSAGE
        ) VALUES (
          P_PLAN_ID, REC.INVENTORY_ITEM_ID, 'BUY',
          V_NET_QTY, REC.REQUIREMENT_DATE,
          REC.REQUIREMENT_DATE - V_LEAD_TIME,
          'Sales Order Demand: Shortage Detected. Raise PO.'
        );
      END IF;
    END LOOP;

    COMMIT;
  END GENERATE_PLAN;

END PKG_MRP_ENGINE;
/

CREATE TABLE OE_ORDER_HEADERS_ALL (
  HEADER_ID NUMBER PRIMARY KEY,
  ORDER_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
  CUSTOMER_ID NUMBER REFERENCES AR_CUSTOMERS (CUSTOMER_ID),
  SHIP_TO_SITE_ID NUMBER REFERENCES AR_CUSTOMER_SITES (SITE_ID),
  ORDER_DATE DATE DEFAULT SYSDATE,
  PRICE_LIST_ID NUMBER REFERENCES PRICELIST_HEADERS (LIST_HEADER_ID),
  STATUS VARCHAR2(20) DEFAULT 'ENTERED',
  TOTAL_AMOUNT NUMBER
);

CREATE SEQUENCE SEQ_OE_ORDER_HEADERS_ALL START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_OE_ORDER_HEADERS_ALL
BEFORE INSERT ON OE_ORDER_HEADERS_ALL
FOR EACH ROW
BEGIN
  IF :NEW.HEADER_ID IS NULL THEN
    SELECT SEQ_OE_ORDER_HEADERS_ALL.NEXTVAL INTO :NEW.HEADER_ID FROM dual;
  END IF;
END;
/

CREATE TABLE OE_ORDER_LINES_ALL (
  LINE_ID NUMBER PRIMARY KEY,
  HEADER_ID NUMBER NOT NULL REFERENCES OE_ORDER_HEADERS_ALL (HEADER_ID),
  ITEM_ID NUMBER REFERENCES MTL_SYSTEM_ITEMS (INVENTORY_ITEM_ID),
  QUANTITY NUMBER NOT NULL,
  UNIT_SELLING_PRICE NUMBER,
  TAX_CODE VARCHAR2(20),
  SCHEDULE_SHIP_DATE DATE,
  STATUS VARCHAR2(20) DEFAULT 'OPEN'
);

CREATE SEQUENCE SEQ_OE_ORDER_LINES_ALL START WITH 1 INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TRG_OE_ORDER_LINES_ALL
BEFORE INSERT ON OE_ORDER_LINES_ALL
FOR EACH ROW
BEGIN
  IF :NEW.LINE_ID IS NULL THEN
    SELECT SEQ_OE_ORDER_LINES_ALL.NEXTVAL INTO :NEW.LINE_ID FROM dual;
  END IF;
END;
/
ALTER PACKAGE PKG_MRP_ENGINE COMPILE BODY;

SELECT object_name, status
FROM user_objects
WHERE object_type='PACKAGE BODY'
  AND object_name='PKG_MRP_ENGINE';
  
BEGIN
  PKG_MRP_ENGINE.GENERATE_PLAN(1);
END;
/  

------------------------------------------------------------
-- PKG_ERP_REPORTS
------------------------------------------------------------
CREATE OR REPLACE PACKAGE PKG_ERP_REPORTS AS

  -- Inventory Stock Ledger
  PROCEDURE GET_STOCK_LEDGER (
    P_START_DATE IN DATE,
    P_END_DATE IN DATE,
    P_ORG_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  );

  -- GST Input/Output Register
  PROCEDURE GET_GST_REGISTER (
    P_START_DATE IN DATE,
    P_END_DATE IN DATE,
    P_TYPE IN VARCHAR2, -- 'INPUT' or 'OUTPUT'
    P_CURSOR OUT SYS_REFCURSOR
  );

  -- Inventory Aging
  PROCEDURE GET_INVENTORY_AGING (
    P_ORG_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  );

END PKG_ERP_REPORTS;
/

CREATE OR REPLACE PACKAGE BODY PKG_ERP_REPORTS AS

  PROCEDURE GET_STOCK_LEDGER (
    P_START_DATE IN DATE,
    P_END_DATE IN DATE,
    P_ORG_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT
        I.ITEM_CODE,
        I.DESCRIPTION,
        SUM(CASE WHEN T.TRANSACTION_DATE < P_START_DATE THEN T.TRANSACTION_QUANTITY ELSE 0 END) AS OPENING_BALANCE,
        SUM(CASE WHEN T.TRANSACTION_DATE BETWEEN P_START_DATE AND P_END_DATE AND T.TRANSACTION_QUANTITY > 0 THEN T.TRANSACTION_QUANTITY ELSE 0 END) AS TOTAL_RECEIPTS,
        SUM(CASE WHEN T.TRANSACTION_DATE BETWEEN P_START_DATE AND P_END_DATE AND T.TRANSACTION_QUANTITY < 0 THEN ABS(T.TRANSACTION_QUANTITY) ELSE 0 END) AS TOTAL_ISSUES,
        SUM(T.TRANSACTION_QUANTITY) AS CLOSING_BALANCE
      FROM MTL_MATERIAL_TRANSACTIONS T
      JOIN MTL_SYSTEM_ITEMS I ON T.INVENTORY_ITEM_ID = I.INVENTORY_ITEM_ID
      WHERE T.ORGANIZATION_ID = P_ORG_ID
      GROUP BY I.ITEM_CODE, I.DESCRIPTION;
  END GET_STOCK_LEDGER;

  PROCEDURE GET_GST_REGISTER (
    P_START_DATE IN DATE,
    P_END_DATE IN DATE,
    P_TYPE IN VARCHAR2,
    P_CURSOR OUT SYS_REFCURSOR
  ) IS
  BEGIN
    IF P_TYPE = 'INPUT' THEN
      OPEN P_CURSOR FOR
        SELECT
          H.PO_NUMBER AS DOC_NUMBER,
          H.PO_DATE AS DOC_DATE,
          V.VENDOR_NAME AS PARTY_NAME,
          V.GSTIN_NUMBER,
          I.ITEM_CODE,
          I.HSN_CODE,
          T.TAX_TYPE,
          T.TAX_RATE,
          T.TAX_AMOUNT,
          L.LINE_AMOUNT AS TAXABLE_VALUE
        FROM PO_HEADERS_ALL H
        JOIN PO_LINES_ALL L ON H.PO_HEADER_ID = L.PO_HEADER_ID
        JOIN PO_LINE_TAXES T ON L.PO_LINE_ID = T.PO_LINE_ID
        JOIN AP_VENDORS V ON H.VENDOR_ID = V.VENDOR_ID
        JOIN MTL_SYSTEM_ITEMS I ON L.ITEM_ID = I.INVENTORY_ITEM_ID
       WHERE H.PO_DATE BETWEEN P_START_DATE AND P_END_DATE;
    ELSE
      OPEN P_CURSOR FOR
        SELECT
          OH.ORDER_NUMBER AS DOC_NUMBER,
          OH.ORDER_DATE AS DOC_DATE,
          C.CUSTOMER_NAME AS PARTY_NAME,
          CS.GSTIN_NUMBER,
          I.ITEM_CODE,
          I.HSN_CODE,
          'IGST' AS TAX_TYPE,
          18 AS TAX_RATE,
          (NVL(OL.UNIT_SELLING_PRICE,0) * NVL(OL.QUANTITY,0) * 0.18) AS TAX_AMOUNT,
          (NVL(OL.UNIT_SELLING_PRICE,0) * NVL(OL.QUANTITY,0)) AS TAXABLE_VALUE
        FROM OE_ORDER_HEADERS_ALL OH
        JOIN OE_ORDER_LINES_ALL OL ON OH.HEADER_ID = OL.HEADER_ID
        JOIN AR_CUSTOMERS C ON OH.CUSTOMER_ID = C.CUSTOMER_ID
        JOIN AR_CUSTOMER_SITES CS ON OH.SHIP_TO_SITE_ID = CS.SITE_ID
        JOIN MTL_SYSTEM_ITEMS I ON OL.ITEM_ID = I.INVENTORY_ITEM_ID
       WHERE OH.ORDER_DATE BETWEEN P_START_DATE AND P_END_DATE;
    END IF;
  END GET_GST_REGISTER;

  PROCEDURE GET_INVENTORY_AGING (
    P_ORG_ID IN NUMBER,
    P_CURSOR OUT SYS_REFCURSOR
  ) IS
  BEGIN
    OPEN P_CURSOR FOR
      SELECT
        I.ITEM_CODE,
        I.DESCRIPTION,
        SUM(CASE WHEN (SYSDATE - T.TRANSACTION_DATE) <= 30 THEN T.TRANSACTION_QUANTITY ELSE 0 END) AS AGE_0_30_DAYS,
        SUM(CASE WHEN (SYSDATE - T.TRANSACTION_DATE) BETWEEN 31 AND 60 THEN T.TRANSACTION_QUANTITY ELSE 0 END) AS AGE_31_60_DAYS,
        SUM(CASE WHEN (SYSDATE - T.TRANSACTION_DATE) BETWEEN 61 AND 90 THEN T.TRANSACTION_QUANTITY ELSE 0 END) AS AGE_61_90_DAYS,
        SUM(CASE WHEN (SYSDATE - T.TRANSACTION_DATE) > 90 THEN T.TRANSACTION_QUANTITY ELSE 0 END) AS AGE_OVER_90_DAYS,
        SUM(T.TRANSACTION_QUANTITY) * NVL(I.LIST_PRICE_PER_UNIT,0) AS TOTAL_VALUE
      FROM MTL_MATERIAL_TRANSACTIONS T
      JOIN MTL_SYSTEM_ITEMS I ON T.INVENTORY_ITEM_ID = I.INVENTORY_ITEM_ID
      WHERE T.ORGANIZATION_ID = P_ORG_ID
        AND T.TRANSACTION_QUANTITY > 0
      GROUP BY I.ITEM_CODE, I.DESCRIPTION, I.LIST_PRICE_PER_UNIT;
  END GET_INVENTORY_AGING;

END PKG_ERP_REPORTS;
/

------------------------------------------------------------
-- MV_SALES_SUMMARY_BY_REGION
------------------------------------------------------------
CREATE MATERIALIZED VIEW MV_SALES_SUMMARY_BY_REGION
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
  TO_CHAR(OH.ORDER_DATE,'YYYY') AS SALES_YEAR,
  CS.STATE AS REGION,
  I.ITEM_CATEGORY,
  SUM(OL.QUANTITY) AS TOTAL_UNITS,
  SUM(NVL(OL.UNIT_SELLING_PRICE,0) * NVL(OL.QUANTITY,0)) AS TOTAL_REVENUE
FROM OE_ORDER_HEADERS_ALL OH
JOIN OE_ORDER_LINES_ALL OL ON OH.HEADER_ID = OL.HEADER_ID
JOIN AR_CUSTOMER_SITES CS ON OH.SHIP_TO_SITE_ID = CS.SITE_ID
JOIN MTL_SYSTEM_ITEMS I ON OL.ITEM_ID = I.INVENTORY_ITEM_ID
GROUP BY TO_CHAR(OH.ORDER_DATE,'YYYY'), CS.STATE, I.ITEM_CATEGORY;

------------------------------------------------------------
-- MV_PURCHASE_SUMMARY
------------------------------------------------------------
CREATE MATERIALIZED VIEW MV_PURCHASE_SUMMARY
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
  TO_CHAR(PH.PO_DATE,'YYYY') AS PURCHASE_YEAR,
  V.VENDOR_NAME,
  V.GSTIN_NUMBER,
  COUNT(PH.PO_HEADER_ID) AS TOTAL_POS,
  SUM(NVL(PH.GRAND_TOTAL_AMOUNT,0)) AS TOTAL_SPEND
FROM PO_HEADERS_ALL PH
JOIN AP_VENDORS V ON PH.VENDOR_ID = V.VENDOR_ID
GROUP BY TO_CHAR(PH.PO_DATE,'YYYY'), V.VENDOR_NAME, V.GSTIN_NUMBER;

------------------------------------------------------------
-- Sample items (MRI BOM)
------------------------------------------------------------
BEGIN
  INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, IS_SALEABLE, SERIAL_CONTROL_CODE, LEAD_TIME_DAYS, CREATED_BY)
  VALUES (101, 'MRI-SYS-1.5T', '1.5 Tesla Superconducting MRI Scanner System', 'NOS', 'FINISHED_GOOD', 'IMAGING', '90181300', 'Y', 'AT_RECEIPT', 45, 'SYSTEM');

  INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, IS_SALEABLE, SERIAL_CONTROL_CODE, LEAD_TIME_DAYS, CREATED_BY)
  VALUES (101, 'MRI-SYS-3.0T', '3.0 Tesla High-Field MRI Scanner System', 'NOS', 'FINISHED_GOOD', 'IMAGING', '90181300', 'Y', 'AT_RECEIPT', 60, 'SYSTEM');

  INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, SERIAL_CONTROL_CODE, LEAD_TIME_DAYS, CREATED_BY)
  VALUES (101, 'SA-MAGNET-1.5T', '1.5T Niobium-Titanium Superconducting Magnet Assembly', 'NOS', 'SUB_ASSEMBLY', 'MAGNET', '8505', 'AT_RECEIPT', 30, 'SYSTEM');

  INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, LOT_CONTROL_CODE, LEAD_TIME_DAYS, CREATED_BY)
  VALUES (101, 'SA-GRADIENT-SET', 'X-Y-Z Gradient Coil Assembly (Resistive)', 'SET', 'SUB_ASSEMBLY', 'COIL', '8505', 'FULL_CONTROL', 20, 'SYSTEM');

  INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, LEAD_TIME_DAYS, CREATED_BY)
  VALUES (101, 'SA-RF-BODY-COIL', 'Integrated RF Body Transmit/Receive Coil', 'NOS', 'SUB_ASSEMBLY', 'RF_SYS', '8543', 15, 'SYSTEM');

  INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, LOT_CONTROL_CODE, LEAD_TIME_DAYS, CREATED_BY)
  VALUES (101, 'RM-WIRE-NBTI', 'Multifilamentary Niobium-Titanium Superconducting Wire', 'MTR', 'RAW_MATERIAL', 'WIRE', '7229', 'FULL_CONTROL', 60, 'SYSTEM');

  INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, LOT_CONTROL_CODE, LEAD_TIME_DAYS, CREATED_BY)
  VALUES (101, 'RM-HE-LIQUID', 'Liquid Helium (Cryogenic Coolant)', 'LTR', 'RAW_MATERIAL', 'GAS', '28042910', 'FULL_CONTROL', 7, 'SYSTEM');

  INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, LEAD_TIME_DAYS, CREATED_BY)
  VALUES (101, 'RM-SS-316L-SHEET', 'Stainless Steel 316L Sheet (Non-Magnetic)', 'KG', 'RAW_MATERIAL', 'METAL', '7219', 14, 'SYSTEM');

  INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, LEAD_TIME_DAYS, CREATED_BY)
  VALUES (101, 'RM-PCB-AMP', 'Low Noise Amplifier (LNA) Circuit Board', 'NOS', 'RAW_MATERIAL', 'ELECTRONICS', '8534', 25, 'SYSTEM');

  COMMIT;
END;
/

------------------------------------------------------------
-- Sample vendors and customers
------------------------------------------------------------
BEGIN
  INSERT INTO AP_VENDORS (VENDOR_NAME, VENDOR_CODE, VENDOR_TYPE, COUNTRY, CURRENCY_CODE, STATE, CREATED_BY)
  VALUES ('Luvata Superconductors', 'SUP-LUV-001', 'OEM', 'FINLAND', 'EUR', NULL, 'SYSTEM');

  INSERT INTO AP_VENDORS (VENDOR_NAME, VENDOR_CODE, VENDOR_TYPE, COUNTRY, CURRENCY_CODE, STATE, CREATED_BY)
  VALUES ('Bruker EST', 'SUP-BRU-002', 'OEM', 'GERMANY', 'EUR', NULL, 'SYSTEM');

  INSERT INTO AP_VENDORS (VENDOR_NAME, VENDOR_CODE, VENDOR_TYPE, GSTIN_NUMBER, CITY, STATE, COUNTRY, CREATED_BY)
  VALUES ('Linde India Ltd', 'SUP-LIN-003', 'DISTRIBUTOR', '29AAACL0000A1Z5', 'Bangalore', 'Karnataka', 'INDIA', 'SYSTEM');

  INSERT INTO AP_VENDORS (VENDOR_NAME, VENDOR_CODE, VENDOR_TYPE, GSTIN_NUMBER, CITY, STATE, COUNTRY, CREATED_BY)
  VALUES ('Inox Air Products', 'SUP-INOX-004', 'DISTRIBUTOR', '27AAACI0000A1Z5', 'Mumbai', 'Maharashtra', 'INDIA', 'SYSTEM');

  INSERT INTO AP_VENDORS (VENDOR_NAME, VENDOR_CODE, VENDOR_TYPE, GSTIN_NUMBER, STATE, COUNTRY, CREATED_BY)
  VALUES ('Jindal Stainless', 'SUP-JIN-005', 'OEM', '06AAACJ0000A1Z5', 'Haryana', 'INDIA', 'SYSTEM');

  INSERT INTO AR_CUSTOMERS (CUSTOMER_NAME, CUSTOMER_NUMBER, CUSTOMER_CATEGORY, CREATED_BY)
  VALUES ('Apollo Hospitals Enterprise', 'CUST-APO-001', 'HOSPITAL', 'SYSTEM');

  INSERT INTO AR_CUSTOMERS (CUSTOMER_NAME, CUSTOMER_NUMBER, CUSTOMER_CATEGORY, CREATED_BY)
  VALUES ('Medanta The Medicity', 'CUST-MED-002', 'HOSPITAL', 'SYSTEM');

  COMMIT;
END;
/

SELECT * FROM MTL_SYSTEM_ITEMS;
SELECT * FROM AP_VENDORS;

VARIABLE rc REFCURSOR;
EXEC PKG_ERP_REPORTS.GET_STOCK_LEDGER(SYSDATE-30, SYSDATE, 101, :rc);
PRINT rc;

-- Cryogen suppliers
INSERT INTO AP_VENDORS (VENDOR_NAME, VENDOR_CODE, VENDOR_TYPE, GSTIN_NUMBER, CITY, STATE, COUNTRY, CREATED_BY)
VALUES ('Air Liquide India', 'SUP-ALI-006', 'DISTRIBUTOR', '29AAACA0000A1Z5', 'Bangalore', 'Karnataka', 'INDIA', 'SYSTEM');

INSERT INTO AP_VENDORS (VENDOR_NAME, VENDOR_CODE, VENDOR_TYPE, GSTIN_NUMBER, CITY, STATE, COUNTRY, CREATED_BY)
VALUES ('BOC India Ltd', 'SUP-BOC-007', 'DISTRIBUTOR', '27AAACB0000A1Z5', 'Mumbai', 'Maharashtra', 'INDIA', 'SYSTEM');

-- Electronics suppliers
INSERT INTO AP_VENDORS (VENDOR_NAME, VENDOR_CODE, VENDOR_TYPE, COUNTRY, CURRENCY_CODE, CREATED_BY)
VALUES ('Texas Instruments', 'SUP-TI-008', 'OEM', 'USA', 'USD', 'SYSTEM');

INSERT INTO AP_VENDORS (VENDOR_NAME, VENDOR_CODE, VENDOR_TYPE, COUNTRY, CURRENCY_CODE, CREATED_BY)
VALUES ('Analog Devices', 'SUP-ADI-009', 'OEM', 'USA', 'USD', 'SYSTEM');


-- Hospitals
INSERT INTO AR_CUSTOMERS (CUSTOMER_NAME, CUSTOMER_NUMBER, CUSTOMER_CATEGORY, CREATED_BY)
VALUES ('Fortis Healthcare', 'CUST-FOR-003', 'HOSPITAL', 'SYSTEM');

INSERT INTO AR_CUSTOMERS (CUSTOMER_NAME, CUSTOMER_NUMBER, CUSTOMER_CATEGORY, CREATED_BY)
VALUES ('Max Healthcare', 'CUST-MAX-004', 'HOSPITAL', 'SYSTEM');

-- Diagnostic centers
INSERT INTO AR_CUSTOMERS (CUSTOMER_NAME, CUSTOMER_NUMBER, CUSTOMER_CATEGORY, CREATED_BY)
VALUES ('Dr Lal PathLabs', 'CUST-LAL-005', 'DIAGNOSTIC_CENTER', 'SYSTEM');


-- Gradient coil set
INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, LEAD_TIME_DAYS, CREATED_BY)
VALUES (101, 'SA-GRADIENT-3T', '3T Gradient Coil Assembly', 'SET', 'SUB_ASSEMBLY', 'COIL', '8505', 25, 'SYSTEM');

-- RF Head Coil
INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, LEAD_TIME_DAYS, CREATED_BY)
VALUES (101, 'SA-RF-HEAD-COIL', 'RF Head Coil for Neuro Imaging', 'NOS', 'SUB_ASSEMBLY', 'RF_SYS', '8543', 20, 'SYSTEM');

-- Cryogenic Dewar
INSERT INTO MTL_SYSTEM_ITEMS (ORGANIZATION_ID, ITEM_CODE, DESCRIPTION, PRIMARY_UOM_CODE, ITEM_TYPE, ITEM_CATEGORY, HSN_CODE, LEAD_TIME_DAYS, CREATED_BY)
VALUES (101, 'RM-DEWAR-100L', '100L Cryogenic Dewar for Helium', 'NOS', 'RAW_MATERIAL', 'CRYO', '7311', 10, 'SYSTEM');

-- Purchase Order for Liquid Helium (Intra-state: Karnataka vendor, plant also in Karnataka)
INSERT INTO PO_HEADERS_ALL (PO_NUMBER, VENDOR_ID, CURRENCY_CODE, STATUS, TOTAL_LINE_AMOUNT)
VALUES ('PO-2001', 6, 'INR', 'APPROVED', 100000);

INSERT INTO PO_LINES_ALL (PO_HEADER_ID, LINE_NUM, ITEM_ID, QUANTITY, UNIT_PRICE, HSN_CODE, GST_TAX_RATE)
VALUES (1, 1, (SELECT INVENTORY_ITEM_ID FROM MTL_SYSTEM_ITEMS WHERE ITEM_CODE='RM-HE-LIQUID'), 500, 200, '28042910', 18);

-- Purchase Order for Gradient Coil (Inter-state: Maharashtra vendor, plant in Karnataka)
INSERT INTO PO_HEADERS_ALL (PO_NUMBER, VENDOR_ID, CURRENCY_CODE, STATUS, TOTAL_LINE_AMOUNT)
VALUES ('PO-2002', 7, 'INR', 'APPROVED', 250000);

INSERT INTO PO_LINES_ALL (PO_HEADER_ID, LINE_NUM, ITEM_ID, QUANTITY, UNIT_PRICE, HSN_CODE, GST_TAX_RATE)
VALUES (2, 1, (SELECT INVENTORY_ITEM_ID FROM MTL_SYSTEM_ITEMS WHERE ITEM_CODE='SA-GRADIENT-3T'), 2, 125000, '8505', 18);

BEGIN
  PKG_GST_CALCULATOR.CALCULATE_PO_TAX(1); -- PO-2001
END;
/
SET SERVEROUTPUT ON;
SELECT * FROM PO_LINE_TAXES WHERE PO_LINE_ID IN (SELECT PO_LINE_ID FROM PO_LINES_ALL WHERE PO_HEADER_ID=1);


--------------------------
BEGIN
  PKG_GST_CALCULATOR.CALCULATE_PO_TAX(2); -- PO-2002
END;
/

SELECT * FROM PO_LINE_TAXES WHERE PO_LINE_ID IN (SELECT PO_LINE_ID FROM PO_LINES_ALL WHERE PO_HEADER_ID=2);






